import { makeStyles } from "@material-ui/core/styles";
import Box from "@material-ui/core/Box";
import Handsontable from "handsontable";
import { HotTable, HotColumn } from "@handsontable/react";
import React, { useState, useEffect } from "react";
import { useQuery } from "@apollo/client";
import { LIST_ALL_PROPERTY } from "../../helpers/graphql/queries";

//components
import { Layout, Tab } from "../../components";

const Home = () => {
	const [toggle, setToggle] = useState<boolean>(false);

	const toggler = () => {
		setToggle(!toggle);
	};

	//tab handler
	const [open, setOpen] = useState<boolean>(false);

	const handleOpen = () => {
		setOpen(true);
	};

	const handleClose = () => {
		setOpen(false);
	};

	useEffect((): void => {
		document.body.addEventListener("dblclick", function (e) {
			handleOpen();
			// alert(hotter.getSelected());
		});
	}, []);

	// const hotTableComponent = React.createRef();

	const useStyles = makeStyles((theme) => ({
		container: {
			height: "100vh",
			display: "flex",
			// overflowX: "hidden",
		},
		box: {
			width: "100%",
			// overflowX: "hidden",
		},
		main: {
			width: "100%",
			height: "calc(100% - 50px)",
			display: "flex",
			//zIndex: -10,
			// overflowX: "hidden",
		},
		mainBox: {
			backgroundColor: "white",
			height: "95%", //make it 97% on toggle
			width: toggle ? "97%" : "95%",
			// width: "95%",
			margin: "auto auto",
			overflowX: "scroll",
			position: "relative",
			display: "flex",
			// flex: "1 1 0",
			justifyContent: "center",
		},
	}));
	const classes = useStyles();

	const { loading, error, data } = useQuery(LIST_ALL_PROPERTY);

	// if (loading) return <p>Loading...</p>;
	// if (error) return <p>Error :(</p>;

	console.log(data?.list_all_property_reports.edges);

	const [state, setState] = useState({
		// data: data?.list_all_property_reports?.edges,
		// data: [
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52de5d4be594fba8e7",
		// 		auction_event_id: "b3154d99-b0ba-4039-a27b-c046a19f75b1",
		// 		address_street: "860 Ashland Place",
		// 		address_city: "Alamo, Maryland, 2062",
		// 		address_county: "SAINT CHARLES",
		// 		address_state: "IL",
		// 		address_zip: 749,
		// 		credit_bid: 96535,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Unknown",
		// 		bed_rooms: 3,
		// 		bath_rooms: 3,
		// 		square_feet: 1283,
		// 		lot_size: 74.751153,
		// 		year_built: "2015-09-16T07:25:52 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 87795,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2018-10-10T07:48:54 -01:00",
		// 		bidding_end_time: "2014-04-23T07:11:49 -01:00",
		// 		broker_first_name: "Araceli",
		// 		broker_last_name: "Kelly",
		// 		broker_email: "aracelikelly@typhonica.com",
		// 		broker_phone: "+1 (921) 573-3908",
		// 		previous_listed_price: -58.361276,
		// 		run_number: 55,
		// 		interior_access: true,
		// 		red_bell: 72525,
		// 		zillow: 75212,
		// 	},
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52af848737b9b2b31b",
		// 		auction_event_id: "0ae3b2d1-575e-4774-aceb-f90822328278",
		// 		address_street: "874 Summit Street",
		// 		address_city: "Iberia, Alaska, 8181",
		// 		address_county: "MARSHALL",
		// 		address_state: "LA",
		// 		address_zip: 9609,
		// 		credit_bid: 94727,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Manuf/Mobile",
		// 		bed_rooms: 2,
		// 		bath_rooms: 2,
		// 		square_feet: 706,
		// 		lot_size: 30.049034,
		// 		year_built: "2019-05-13T12:15:11 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 86899,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2017-01-23T01:12:53 -01:00",
		// 		bidding_end_time: "2015-09-18T03:13:40 -01:00",
		// 		broker_first_name: "Samantha",
		// 		broker_last_name: "Albert",
		// 		broker_email: "samanthaalbert@typhonica.com",
		// 		broker_phone: "+1 (989) 442-3963",
		// 		previous_listed_price: 21.632882,
		// 		run_number: 167,
		// 		interior_access: true,
		// 		red_bell: 88709,
		// 		zillow: 95492,
		// 	},
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52de5d4be594fba8e7",
		// 		auction_event_id: "b3154d99-b0ba-4039-a27b-c046a19f75b1",
		// 		address_street: "860 Ashland Place",
		// 		address_city: "Alamo, Maryland, 2062",
		// 		address_county: "SAINT CHARLES",
		// 		address_state: "IL",
		// 		address_zip: 749,
		// 		credit_bid: 96535,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Unknown",
		// 		bed_rooms: 3,
		// 		bath_rooms: 3,
		// 		square_feet: 1283,
		// 		lot_size: 74.751153,
		// 		year_built: "2015-09-16T07:25:52 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 87795,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2018-10-10T07:48:54 -01:00",
		// 		bidding_end_time: "2014-04-23T07:11:49 -01:00",
		// 		broker_first_name: "Araceli",
		// 		broker_last_name: "Kelly",
		// 		broker_email: "aracelikelly@typhonica.com",
		// 		broker_phone: "+1 (921) 573-3908",
		// 		previous_listed_price: -58.361276,
		// 		run_number: 55,
		// 		interior_access: true,
		// 		red_bell: 72525,
		// 		zillow: 75212,
		// 	},
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52af848737b9b2b31b",
		// 		auction_event_id: "0ae3b2d1-575e-4774-aceb-f90822328278",
		// 		address_street: "874 Summit Street",
		// 		address_city: "Iberia, Alaska, 8181",
		// 		address_county: "MARSHALL",
		// 		address_state: "LA",
		// 		address_zip: 9609,
		// 		credit_bid: 94727,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Manuf/Mobile",
		// 		bed_rooms: 2,
		// 		bath_rooms: 2,
		// 		square_feet: 706,
		// 		lot_size: 30.049034,
		// 		year_built: "2019-05-13T12:15:11 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 86899,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2017-01-23T01:12:53 -01:00",
		// 		bidding_end_time: "2015-09-18T03:13:40 -01:00",
		// 		broker_first_name: "Samantha",
		// 		broker_last_name: "Albert",
		// 		broker_email: "samanthaalbert@typhonica.com",
		// 		broker_phone: "+1 (989) 442-3963",
		// 		previous_listed_price: 21.632882,
		// 		run_number: 167,
		// 		interior_access: true,
		// 		red_bell: 88709,
		// 		zillow: 95492,
		// 	},
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52de5d4be594fba8e7",
		// 		auction_event_id: "b3154d99-b0ba-4039-a27b-c046a19f75b1",
		// 		address_street: "860 Ashland Place",
		// 		address_city: "Alamo, Maryland, 2062",
		// 		address_county: "SAINT CHARLES",
		// 		address_state: "IL",
		// 		address_zip: 749,
		// 		credit_bid: 96535,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Unknown",
		// 		bed_rooms: 3,
		// 		bath_rooms: 3,
		// 		square_feet: 1283,
		// 		lot_size: 74.751153,
		// 		year_built: "2015-09-16T07:25:52 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 87795,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2018-10-10T07:48:54 -01:00",
		// 		bidding_end_time: "2014-04-23T07:11:49 -01:00",
		// 		broker_first_name: "Araceli",
		// 		broker_last_name: "Kelly",
		// 		broker_email: "aracelikelly@typhonica.com",
		// 		broker_phone: "+1 (921) 573-3908",
		// 		previous_listed_price: -58.361276,
		// 		run_number: 55,
		// 		interior_access: true,
		// 		red_bell: 72525,
		// 		zillow: 75212,
		// 	},
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52af848737b9b2b31b",
		// 		auction_event_id: "0ae3b2d1-575e-4774-aceb-f90822328278",
		// 		address_street: "874 Summit Street",
		// 		address_city: "Iberia, Alaska, 8181",
		// 		address_county: "MARSHALL",
		// 		address_state: "LA",
		// 		address_zip: 9609,
		// 		credit_bid: 94727,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Manuf/Mobile",
		// 		bed_rooms: 2,
		// 		bath_rooms: 2,
		// 		square_feet: 706,
		// 		lot_size: 30.049034,
		// 		year_built: "2019-05-13T12:15:11 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 86899,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2017-01-23T01:12:53 -01:00",
		// 		bidding_end_time: "2015-09-18T03:13:40 -01:00",
		// 		broker_first_name: "Samantha",
		// 		broker_last_name: "Albert",
		// 		broker_email: "samanthaalbert@typhonica.com",
		// 		broker_phone: "+1 (989) 442-3963",
		// 		previous_listed_price: 21.632882,
		// 		run_number: 167,
		// 		interior_access: true,
		// 		red_bell: 88709,
		// 		zillow: 95492,
		// 	},
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52de5d4be594fba8e7",
		// 		auction_event_id: "b3154d99-b0ba-4039-a27b-c046a19f75b1",
		// 		address_street: "860 Ashland Place",
		// 		address_city: "Alamo, Maryland, 2062",
		// 		address_county: "SAINT CHARLES",
		// 		address_state: "IL",
		// 		address_zip: 749,
		// 		credit_bid: 96535,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Unknown",
		// 		bed_rooms: 3,
		// 		bath_rooms: 3,
		// 		square_feet: 1283,
		// 		lot_size: 74.751153,
		// 		year_built: "2015-09-16T07:25:52 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 87795,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2018-10-10T07:48:54 -01:00",
		// 		bidding_end_time: "2014-04-23T07:11:49 -01:00",
		// 		broker_first_name: "Araceli",
		// 		broker_last_name: "Kelly",
		// 		broker_email: "aracelikelly@typhonica.com",
		// 		broker_phone: "+1 (921) 573-3908",
		// 		previous_listed_price: -58.361276,
		// 		run_number: 55,
		// 		interior_access: true,
		// 		red_bell: 72525,
		// 		zillow: 75212,
		// 	},
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52af848737b9b2b31b",
		// 		auction_event_id: "0ae3b2d1-575e-4774-aceb-f90822328278",
		// 		address_street: "874 Summit Street",
		// 		address_city: "Iberia, Alaska, 8181",
		// 		address_county: "MARSHALL",
		// 		address_state: "LA",
		// 		address_zip: 9609,
		// 		credit_bid: 94727,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Manuf/Mobile",
		// 		bed_rooms: 2,
		// 		bath_rooms: 2,
		// 		square_feet: 706,
		// 		lot_size: 30.049034,
		// 		year_built: "2019-05-13T12:15:11 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 86899,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2017-01-23T01:12:53 -01:00",
		// 		bidding_end_time: "2015-09-18T03:13:40 -01:00",
		// 		broker_first_name: "Samantha",
		// 		broker_last_name: "Albert",
		// 		broker_email: "samanthaalbert@typhonica.com",
		// 		broker_phone: "+1 (989) 442-3963",
		// 		previous_listed_price: 21.632882,
		// 		run_number: 167,
		// 		interior_access: true,
		// 		red_bell: 88709,
		// 		zillow: 95492,
		// 	},
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52de5d4be594fba8e7",
		// 		auction_event_id: "b3154d99-b0ba-4039-a27b-c046a19f75b1",
		// 		address_street: "860 Ashland Place",
		// 		address_city: "Alamo, Maryland, 2062",
		// 		address_county: "SAINT CHARLES",
		// 		address_state: "IL",
		// 		address_zip: 749,
		// 		credit_bid: 96535,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Unknown",
		// 		bed_rooms: 3,
		// 		bath_rooms: 3,
		// 		square_feet: 1283,
		// 		lot_size: 74.751153,
		// 		year_built: "2015-09-16T07:25:52 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 87795,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2018-10-10T07:48:54 -01:00",
		// 		bidding_end_time: "2014-04-23T07:11:49 -01:00",
		// 		broker_first_name: "Araceli",
		// 		broker_last_name: "Kelly",
		// 		broker_email: "aracelikelly@typhonica.com",
		// 		broker_phone: "+1 (921) 573-3908",
		// 		previous_listed_price: -58.361276,
		// 		run_number: 55,
		// 		interior_access: true,
		// 		red_bell: 72525,
		// 		zillow: 75212,
		// 	},
		// 	{
		// 		checked: "yes",
		// 		property_id: "60293c52af848737b9b2b31b",
		// 		auction_event_id: "0ae3b2d1-575e-4774-aceb-f90822328278",
		// 		address_street: "874 Summit Street",
		// 		address_city: "Iberia, Alaska, 8181",
		// 		address_county: "MARSHALL",
		// 		address_state: "LA",
		// 		address_zip: 9609,
		// 		credit_bid: 94727,
		// 		display_reserve: "",
		// 		inspection_report: "http://placehold.it/32x32",
		// 		property_type: "Manuf/Mobile",
		// 		bed_rooms: 2,
		// 		bath_rooms: 2,
		// 		square_feet: 706,
		// 		lot_size: 30.049034,
		// 		year_built: "2019-05-13T12:15:11 -01:00",
		// 		mls_comment: "",
		// 		starting_bid: 86899,
		// 		occupancy_status: "Vacant",
		// 		product_type: "REO",
		// 		bidding_start_time: "2017-01-23T01:12:53 -01:00",
		// 		bidding_end_time: "2015-09-18T03:13:40 -01:00",
		// 		broker_first_name: "Samantha",
		// 		broker_last_name: "Albert",
		// 		broker_email: "samanthaalbert@typhonica.com",
		// 		broker_phone: "+1 (989) 442-3963",
		// 		previous_listed_price: 21.632882,
		// 		run_number: 167,
		// 		interior_access: true,
		// 		red_bell: 88709,
		// 		zillow: 95492,
		// 	},
		// ],
		// rowHeaders: true,
		rowHeights: 30,
		columnHeaderHeight: 35,
		columns: [
			{
				data: "checked",
				type: "checkbox",
				checkedTemplate: "yes",
				uncheckedTemplate: "no",
				className: "htCenter",
			},
			{ data: "property_id" },
			{ data: "r" },
			{ data: "auction_event_id" },
			{ data: "seller_code" },
			{ data: "auction_start_date" },
			{ data: "auction_end_date" },
			{ data: "address_street" },
			{ data: "address_city" },
			{ data: "address_state" },
			{ data: "address_zip" },
			{ data: "address_county" },
			{ data: "credit_bid" },
			{ data: "auction_list_price" },
			{ data: "rsrv" },
			{ data: "st_rsrv" },
			{ data: "buy_price" },
			{ data: "rehabilitation_cost" },
			{ data: "resale_price" },
			{ data: "profit" },
			{ data: "return_on_investment" },
			{ data: "auction_agent" },
			{ data: "auction_agent_number" },
			{ data: "auction_agent_email" },
			{ data: "user" },
			{ data: "property_status" },
			{ data: "reason" },
			{ data: "note" },
			{ data: "access" },
			{ data: "reason" },
			{ data: "occupancy" },
			{ data: "product" },
			{ data: "prop_type" },
			{ data: "sqft" },
			{ data: "bed_rooms" },
			{ data: "bath_rooms" },
			{ data: "lot_size" },
			{ data: "sb" },
			{ data: "bid_history" },
			{ data: "bought_date" },
			{ data: "sold_date" },
			{ data: "sold_price" },
			{ data: "auction_status" },
		],
		autoWrapRow: true,
		collapsibleColumns: true,
		minCols: 44,
		className: "htMiddle",
		// hiddenColumns: true,
		exportFile: true,
		manualRowMove: true,
		manualColumnMove: true,
		contextMenu: true,
		filters: true,
		dropdownMenu: true,
		manualRowResize: true,
		manualColumnResize: true,
		//rowHeaders: true,
		// rowHeaders: ["checkbox", ""],
		colHeaders: [
			"",
			"Property ID",
			"R",
			"Event Id",
			"Seller",
			"Auction Start Date",
			"Auction End Date",
			"Address",
			"City",
			"ST",
			"Zip",
			"Country",
			"Credit Bid",
			"Auction List Price ($)",
			"RSRV",
			"ST RSV ($)",
			"Buy Price ($)",
			"Rehab ($)",
			"Resale ($)",
			"Profit ($)",
			"ROI",
			"Auction Agent",
			"Auction Agent Number",
			"Auction Agent Email",
			"User",
			"Status",
			"Reason",
			"Note",
			"Access",
			"Occupancy",
			"Product",
			"Prop Type",
			"SQFT",
			"BR",
			"BA",
			"Lot",
			"Year",
			"SB",
			"Bid History",
			"Bought Date",
			"Sold Date",
			"Sold Price",
			"Auction Status",
		],
		licenseKey: "non-commercial-and-evaluation",
	});

	return (
		<>
			<Layout>
				<Box className={classes.mainBox}>
					{data?.list_all_property_reports?.edges && (
						<HotTable
							settings={state}
							id="hot"
							data={data?.list_all_property_reports?.edges}

							// rowHeaders={[

							// 		type: "checkbox",
							// 		checkedTemplate: "yes",
							// 		uncheckedTemplate: "no",

							// ]}
						>
							{/* <HotColumn width={100}></HotColumn>
								<HotColumn width={150}></HotColumn>
								<HotColumn width={150}></HotColumn> */}
						</HotTable>
					)}
					{open ? <Tab toggle={toggle} handleClose={handleClose} /> : ""}
				</Box>
			</Layout>
		</>
	);
};
export default Home;
